### ISSUE TITLE
segfault on cygwin

### ISSUE THREAD

**Issue by djhenderson** [skeeto/dynamic-function-benchmark#1]
benchmark compiles _as is_ on cygwin, but generates a segment fault while trying to perform the jit benchmark. gdb was no help, but I observed that the compilation warned about redefining PAGESIZE from 65536 to 4096. The <strike>attached</strike> included patch compensates for this, and allows the benchmark to execute successfully giving these result on my laptop with "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2808 Mhz, 4 Core(s), 8 Logical Processor(s)".

```
$ ./benchmark
jit: 2.447226 ns/call
plt: 2.003026 ns/call
ind: 1.725051 ns/call
```
benchmark.c.patch

```
--- a/benchmark.c
+++ b/benchmark.c
@@ -9,9 +9,11 @@
 #include <unistd.h>
 #include <sys/mman.h>

-#define PAGESIZE           4096
-#define PAGEMASK           (~0xfff)
-#define SAFETY_MARGIN      (1024 * PAGESIZE)
+#if !defined(PAGESIZE)
+    #define PAGESIZE       4096
+#endif
+#define PAGEMASK           (~(PAGESIZE-1))
+#define SAFETY_MARGIN      (1024 * 1024 * 4)
 #define BENCHMARK_SECONDS  2
 #define BENCHMARK_SAMPLES  4

```
(Note: one blank line at end of patch.)

**Comment by skeeto** [comment]
Thanks! My README isn't specific enough since it says "any POSIX system" 
on x86-64 which technically includes Cygwin. However, it's more precise 
to say: requires POSIX.1-2001, x86-64, System V ABI. Since Cygwin 
(mostly) follows the Windows x64 ABI, it doesn't fulfill the last 
requirement. The fact that it works at all is luck.

The main issue is that the JIT compiled function doesn't set up shadow 
space, but fortunately the callee doesn't try to use its shadow space. 
It works, but it's fragile.

Thanks for sharing your benchmarks, especially since they show the 
opposite results of my article. I dug into this and the reason is that, 
for Cygwin's toolchain, the (equivalent of the) PLT stub is what's being 
passed to the JIT compiler, so it ends up going through the PLT. Why 
it's so much worse than the PLT benchmark, I can't explain, but it 
definitely won't be better. I fixed this in 5dfdb73, and the JIT 
compiler is passed the same function used for the indirect call 
benchmark. With this change, the benchmark results are what you'd 
expect. The change has no effect on the Linux systems I tested because 
empty == empty_sym.
